package com.spoolstudio.app.utils

data class NamedColor(
    val name: String,
    val hex: String,
    val aliases: List<String> = emptyList()
)

val knownColors = listOf(
    NamedColor("Transparent", "FFFFFF", listOf("Transparent", "Klar", "Clear", "Natural", "Natur", "Farblos")),

    NamedColor("Black", "000000", listOf("Schwarz", "Jet Black", "Tiefschwarz", "Matt Black", "Gloss Black", "Onyx")),
    NamedColor("Soft Black", "1C1C1C", listOf("Soft Black", "Off Black", "Rich Black")),
    NamedColor("Charcoal", "36454F", listOf("Charcoal", "Holzkohle", "Anthracite Black")),
    NamedColor("Graphite", "474A51", listOf("Graphite", "Graphit", "Graphite Gray", "Graphite Grey")),
    NamedColor("Gunmetal", "2A3439", listOf("Gunmetal", "Gun Metal", "Dunkelmetall")),
    NamedColor("Dark Gray", "4A4A4A", listOf("Dark Grey", "Dunkelgrau", "Anthrazit", "Anthracite")),
    NamedColor("Gray", "808080", listOf("Grey", "Grau", "Neutral Gray", "Neutral Grey", "Mid Gray", "Mid Grey")),
    NamedColor("Cool Gray", "8C92AC", listOf("Cool Grey", "Kühles Grau", "Kuehles Grau")),
    NamedColor("Warm Gray", "8D8070", listOf("Warm Grey", "Warmes Grau", "Greige Gray", "Greige Grey")),
    NamedColor("Light Gray", "D3D3D3", listOf("Light Grey", "Hellgrau", "Ash Gray", "Ash Grey")),
    NamedColor("Silver", "C0C0C0", listOf("Silber", "Metallic Silver", "Silver Gray", "Silver Grey")),
    NamedColor("Pearl Silver", "D9D9D6", listOf("Pearl Silver", "Pearl Grey", "Perlsilber")),
    NamedColor("White", "FFFFFF", listOf("White", "Weiß", "Weiss", "Pure White", "Snow White")),
    NamedColor("Warm White", "FDF4E3", listOf("Warm White", "Warmes Weiß", "Warmes Weiss", "Soft White")),
    NamedColor("Cool White", "F3F8FF", listOf("Cool White", "Kühles Weiß", "Kuehles Weiss", "Ice White")),
    NamedColor("Ivory", "FFFFF0", listOf("Ivory", "Elfenbein")),
    NamedColor("Cream", "FFFDD0", listOf("Cream", "Creme")),
    NamedColor("Vanilla", "F3E5AB", listOf("Vanilla", "Vanille")),
    NamedColor("Champagne", "F7E7CE", listOf("Champagne", "Champagner")),
    NamedColor("Pearl", "F0EAE1", listOf("Pearl", "Perlweiß", "Perlweiss", "Pearl White")),

    NamedColor("Red", "FF0000", listOf("Rot", "Signal Red", "Bright Red", "Primary Red")),
    NamedColor("Scarlet", "FF2400", listOf("Scarlet", "Scharlachrot", "Feuerrot")),
    NamedColor("Crimson", "DC143C", listOf("Crimson", "Karminrot")),
    NamedColor("Cherry Red", "D2042D", listOf("Cherry Red", "Kirschrot")),
    NamedColor("Ruby Red", "9B111E", listOf("Ruby Red", "Rubinrot")),
    NamedColor("Burgundy", "800020", listOf("Burgundy", "Bordeaux", "Weinrot")),
    NamedColor("Maroon", "800000", listOf("Maroon", "Dark Red", "Dunkelrot")),
    NamedColor("Wine Red", "722F37", listOf("Wine Red", "Weinrot Dunkel")),
    NamedColor("Rose Red", "C21E56", listOf("Rose Red", "Rosenrot")),

    NamedColor("Orange", "FFA500", listOf("Orange", "Bright Orange", "Signalorange", "Safety Orange")),
    NamedColor("Tangerine", "F28500", listOf("Tangerine", "Mandarin Orange", "Mandarine")),
    NamedColor("Amber", "FFBF00", listOf("Amber", "Bernstein")),
    NamedColor("Apricot", "FBCEB1", listOf("Apricot", "Aprikose")),
    NamedColor("Peach", "FFE5B4", listOf("Peach", "Pfirsich")),
    NamedColor("Coral", "FF7F50", listOf("Coral", "Koralle")),
    NamedColor("Salmon", "FA8072", listOf("Salmon", "Lachs", "Lachsrosa")),
    NamedColor("Terracotta", "E2725B", listOf("Terracotta", "Terrakotta")),
    NamedColor("Rust", "B7410E", listOf("Rust", "Rost", "Rostorange")),
    NamedColor("Copper", "B87333", listOf("Copper", "Kupfer")),
    NamedColor("Bronze", "CD7F32", listOf("Bronze", "Bronzefarben")),

    NamedColor("Yellow", "FFFF00", listOf("Gelb", "Bright Yellow", "Signal Yellow")),
    NamedColor("Lemon Yellow", "FFF44F", listOf("Lemon Yellow", "Zitronengelb")),
    NamedColor("Golden Yellow", "FFDF00", listOf("Golden Yellow", "Goldgelb")),
    NamedColor("Mustard", "D2B55B", listOf("Mustard", "Senf", "Senfgelb")),
    NamedColor("Gold", "FFD700", listOf("Gold", "Golden", "Metallic Gold")),
    NamedColor("Honey", "D9A441", listOf("Honey", "Honig")),
    NamedColor("Ochre", "CC7722", listOf("Ochre", "Ocker")),

    NamedColor("Brown", "8B4513", listOf("Braun", "Wood Brown", "Classic Brown")),
    NamedColor("Dark Brown", "654321", listOf("Dark Brown", "Dunkelbraun", "Espresso")),
    NamedColor("Chocolate Brown", "7B3F00", listOf("Chocolate", "Schokobraun", "Chocolate Brown")),
    NamedColor("Coffee Brown", "6F4E37", listOf("Coffee", "Kaffee", "Coffee Brown")),
    NamedColor("Mocha", "967969", listOf("Mocha", "Mokka")),
    NamedColor("Cappuccino", "A67B5B", listOf("Cappuccino", "Capuccino")),
    NamedColor("Latte Brown", "D3B7A7", listOf("Latte", "Latte Brown", "Milchkaffee", "Cafe Latte")),
    NamedColor("Caramel", "C68E4D", listOf("Caramel", "Karamell")),
    NamedColor("Camel", "C19A6B", listOf("Camel", "Camel Brown")),
    NamedColor("Tan", "D2B48C", listOf("Tan", "Hellbraun", "Light Brown")),
    NamedColor("Sand", "C2B280", listOf("Sand", "Sandfarben", "Sand Color", "Sandfarben Hell")),
    NamedColor("Warm Beige", "D9C2A3", listOf("Warm Beige", "Warmes Beige")),
    NamedColor("Beige", "F5F5DC", listOf("Beige")),
    NamedColor("Taupe", "B38B6D", listOf("Taupe", "Taupe Brown")),
    NamedColor("Greige", "B7AFA3", listOf("Greige", "Gray Beige", "Grey Beige")),
    NamedColor("Stone", "B8A99A", listOf("Stone", "Stein", "Stone Beige")),
    NamedColor("Khaki", "BDB76B", listOf("Khaki", "Khaki Brown")),
    NamedColor("Nude", "E3BC9A", listOf("Nude", "Skin", "Skin Tone")),
    NamedColor("Clay", "B66A50", listOf("Clay", "Ton", "Lehm")),
    NamedColor("Walnut", "773F1A", listOf("Walnut", "Nussbraun")),
    NamedColor("Mahogany", "7A3B11", listOf("Mahogany", "Mahagoni")),

    NamedColor("Olive", "808000", listOf("Olive", "Oliv")),
    NamedColor("Olive Drab", "6B8E23", listOf("Olive Drab", "Army Green", "Army Green Dark")),
    NamedColor("Sage", "9CAF88", listOf("Sage", "Salbei", "Sage Green")),
    NamedColor("Moss Green", "8A9A5B", listOf("Moss Green", "Moosgrün", "Moosgruen")),
    NamedColor("Forest Green", "228B22", listOf("Forest Green", "Waldgrün", "Waldgruen")),
    NamedColor("Green", "008000", listOf("Grün", "Gruen", "Classic Green", "Bottle Green")),
    NamedColor("Emerald", "50C878", listOf("Emerald", "Smaragd", "Emerald Green")),
    NamedColor("Jade", "00A86B", listOf("Jade", "Jade Green")),
    NamedColor("Lime", "00FF00", listOf("Lime", "Lime Green", "Neon Green", "Hellgrün", "Hellgruen")),
    NamedColor("Apple Green", "8DB600", listOf("Apple Green", "Apfelgrün", "Apfelgruen")),
    NamedColor("Mint", "98FF98", listOf("Mint", "Mint Green", "Mintgrün", "Mintgruen")),
    NamedColor("Pastel Green", "77DD77", listOf("Pastel Green", "Pastellgrün", "Pastellgruen")),
    NamedColor("Seafoam", "9FE2BF", listOf("Seafoam", "Sea Foam", "Meergrün", "Meergruen")),
    NamedColor("Teal", "008080", listOf("Teal", "Petrol", "Blue Green", "Blaugrün", "Blaugruen")),
    NamedColor("Turquoise", "40E0D0", listOf("Turquoise", "Türkis", "Tuerkis")),
    NamedColor("Cyan", "00FFFF", listOf("Cyan", "Aqua")),
    NamedColor("Aqua Blue", "7FDBFF", listOf("Aqua Blue", "Water Blue")),

    NamedColor("Blue", "0000FF", listOf("Blau", "Primary Blue", "Bright Blue")),
    NamedColor("Royal Blue", "4169E1", listOf("Royal Blue", "Königsblau", "Koenigsblau")),
    NamedColor("Ultramarine", "3F00FF", listOf("Ultramarine", "Ultramarin")),
    NamedColor("Cobalt Blue", "0047AB", listOf("Cobalt Blue", "Kobaltblau")),
    NamedColor("Navy", "000080", listOf("Navy", "Navy Blue", "Marineblau", "Marine")),
    NamedColor("Dark Blue", "00008B", listOf("Dark Blue", "Dunkelblau", "Deep Blue")),
    NamedColor("Midnight Blue", "191970", listOf("Midnight Blue", "Mitternachtsblau")),
    NamedColor("Steel Blue", "4682B4", listOf("Steel Blue", "Stahlblau")),
    NamedColor("Sky Blue", "87CEEB", listOf("Sky Blue", "Himmelblau")),
    NamedColor("Light Blue", "ADD8E6", listOf("Light Blue", "Hellblau", "Baby Blue")),
    NamedColor("Ice Blue", "D6F1FF", listOf("Ice Blue", "Eisblau")),
    NamedColor("Powder Blue", "B0E0E6", listOf("Powder Blue", "Puderblau")),
    NamedColor("Azure", "007FFF", listOf("Azure", "Azur", "Azurblau")),

    NamedColor("Purple", "800080", listOf("Purple", "Lila", "Violett")),
    NamedColor("Violet", "8F00FF", listOf("Violet", "Violett Kräftig")),
    NamedColor("Royal Purple", "7851A9", listOf("Royal Purple", "Königslila", "Koenigslila")),
    NamedColor("Lavender", "E6E6FA", listOf("Lavender", "Lavendel")),
    NamedColor("Lilac", "C8A2C8", listOf("Lilac", "Flieder")),
    NamedColor("Plum", "8E4585", listOf("Plum", "Pflaume")),
    NamedColor("Magenta", "FF00FF", listOf("Magenta", "Fuchsia")),
    NamedColor("Hot Pink", "FF69B4", listOf("Hot Pink", "Kräftiges Pink")),
    NamedColor("Pink", "FFC0CB", listOf("Pink", "Rosa")),
    NamedColor("Light Pink", "FFB6C1", listOf("Light Pink", "Hellrosa")),
    NamedColor("Rose", "FF66CC", listOf("Rose", "Rosé", "Rose Pink")),
    NamedColor("Dusty Rose", "C08081", listOf("Dusty Rose", "Altrosa")),
    NamedColor("Mauve", "E0B0FF", listOf("Mauve", "Mauve Pink"))
)
